app:
    resource: '@AppBundle/Controller/'
    type: annotation
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }
login:
    path: /login
    defaults: { _controller: AppBundle:Security:login}    
        
login_check:
    path: /login_check

task_list:
    path: /taskList
    defaults: { _controller: showTaskAction}