app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

task_list:
    path: /taskList/showTask/{id}
    defaults: { _controller: AppBundle:Task:showTask}

add_task:
    path: /taskList/addTask/{ref_id}
    defaults: { _controller: AppBundle:Task:addTask}

delete_task:
    path: /taskList/deleteTask/{id}
    defaults: { _controller: AppBundle:Task:deleteTask}

show_project:
    path: /projectList/showProject
    defaults: { _controller: AppBundle:Project:showProject}

show_project_detail:
    path: /project/showProjectDetail/{id}
    defaults: { _controller: AppBundle:Project:showProjectDetail}