app:
    resource: '@AppBundle/Controller/'
    type: annotation
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }
login:
    path: /login
    defaults: { _controller: AppBundle:Security:login}    
        
login_check:
    path: /login_check
logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout} 

task_list:
    path: /taskList/showTask/{id}
    defaults: { _controller: AppBundle:Task:showTask}

add_task:
    path: /taskList/addTask/{ref_id}
    defaults: { _controller: AppBundle:Task:addTask}

delete_task:
    path: /taskList/deleteTask/{id}
    defaults: { _controller: AppBundle:Task:deleteTask}